# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - care-station

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_dd7a9f200d0c4a2c9467e6dc583a31a7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fa4bf082bb9247dcb147c276363dd524 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_dd7a9f200d0c4a2c9467e6dc583a31a7 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'care-station'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8ceff4e1e6f24f7f8fc07e5e4de79c68 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_dd7a9f200d0c4a2c9467e6dc583a31a7 }}/appsvc/staticsite:${{ github.sha }}'